version: "2"
linters:
  enable:
    - misspell
    - bodyclose
    - containedctx
    - contextcheck
    - errname
    - errorlint
    - exptostd
    - goconst
    - gocritic
    - goheader
    - inamedparam
    - intrange
    - lll
    - modernize
    - nolintlint
    - testifylint
    - unconvert
    - unparam
    - usetesting
    - revive
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
  settings:
    lll:
      line-length: 200
    goheader:
      template-path: ./LICENSE_HEADER.tmpl
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
