version: "2"
linters:
  enable:
    - misspell
    - bodyclose
    - contextcheck
    - errname
    - errorlint
    - exptostd
    - goconst
    - gocritic
    - inamedparam
    - intrange
    - lll
    - modernize
    - nolintlint
    - testifylint
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
  settings:
    lll:
      line-length: 200
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
