steps:
  - label: Release
    agents:
      image: "golang:latest@sha256:2fe82a3f3e006b4f2a316c6a21f62b66e1330ae211d039bb8d1128e12ed57bf1":${GO_VERSION}
      cpu: "8"
      memory: "8G"
    command:
      - ".buildkite/scripts/release.sh"
