steps:
  - label: Release
    agents:
      image: "golang:1.26.3@sha256:6df14f4a4bc9d979a3721f488981e0d1b318006377e473ed23d026796f5f4c0a"
      cpu: "16"
      memory: "24G"
      ephemeralStorage: "40G"
    command:
      - ".buildkite/scripts/release.sh"
