steps:
  - label: Release
    agents:
      image: "golang:1.25.6@sha256:ce63a16e0f7063787ebb4eb28e72d477b00b4726f79874b3205a965ffd797ab2"
      cpu: "16"
      memory: "24G"
      ephemeralStorage: "40G"
    command:
      - ".buildkite/scripts/release.sh"
