steps:
  - label: Release
    agents:
      image: "golang:1.24.0@sha256:2b1cbf278ce05a2a310a3d695ebb176420117a8cfcfcc4e5e68a1bef5f6354da"
      cpu: "16"
      memory: "24G"
      ephemeralStorage: "20G"
    command:
      - ".buildkite/scripts/release.sh"
