steps:
  - label: Release
    agents:
      image: "golang:1.25.0@sha256:9e56f0d0f043a68bb8c47c819e47dc29f6e8f5129b8885bed9d43f058f7f3ed6"
      cpu: "16"
      memory: "24G"
      ephemeralStorage: "20G"
    command:
      - ".buildkite/scripts/release.sh"
