steps:
  - label: Release
    agents:
      image: "golang:1.25.4@sha256:698183780de28062f4ef46f82a79ec0ae69d2d22f7b160cf69f71ea8d98bf25d"
      cpu: "24"
      memory: "48G"
      ephemeralStorage: "60G"
    env:
      GOMEMLIMIT: 44GiB
    command:
      - ".buildkite/scripts/release.sh"
    artifact_paths:
      - "dist/*"
