steps:
  - label: Release
    agents:
      image: "golang:latest@sha256:613a108a4a4b1dfb6923305db791a19d088f77632317cfc3446825c54fb862cd":${GO_VERSION}
      cpu: "8"
      memory: "8G"
    command:
      - ".buildkite/scripts/release.sh"
