steps:
  - label: Release
    agents:
      image: "golang:1.26.5@sha256:3aff6657219a4d9c14e27fb1d8976c49c29fddb70ba835014f477e1c70636647"
      cpu: "16"
      memory: "24G"
      ephemeralStorage: "40G"
    command:
      - ".buildkite/scripts/release.sh"
