steps:
  - label: Release
    agents:
      image: "golang:1.25.5@sha256:20b91eda7a9627c127c0225b0d4e8ec927b476fa4130c6760928b849d769c149"
      cpu: "16"
      memory: "24G"
      ephemeralStorage: "20G"
    command:
      - ".buildkite/scripts/release.sh"
