steps:
  - label: Release
    agents:
      image: "golang:1.23.3@sha256:73f06be4578c9987ce560087e2e2ea6485fb605e3910542cadd8fa09fc5f3e31"
      cpu: "16"
      memory: "24G"
      ephemeralStorage: "20G"
    command:
      - ".buildkite/scripts/release.sh"
