steps:
  - label: Release
    agents:
      image: "golang:1.27.1@sha256:512690a5660563b57d37ecc31129e7f136e831db2aed24a1dbeb8ad7380dc0fa"
      cpu: "16"
      memory: "24G"
      ephemeralStorage: "40G"
    command:
      - ".buildkite/scripts/release.sh"
