steps:
  - label: Release
    agents:
      image: "golang:1.23.1@sha256:4f063a24d429510e512cc730c3330292ff49f3ade3ae79bda8f84a24fa25ecb0"
      cpu: "8"
      memory: "8G"
    command:
      - ".buildkite/scripts/release.sh"
