agents:
  provider: "gcp"
  machineType: "n1-standard-4"
  image: family/terraform-provider-elasticstack-ubuntu-2204
steps:
  - label: Regenerate Kibana client and build provider
    command:
      - ".buildkite/scripts/update-kibana-client.sh"