// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

package prmgmt

import (
	"context"
	"fmt"
	"strings"
	"time"
)

const (
	defaultPullRequestBaseBranch          = "main"
	defaultGeneratedChangelogWorkflowHead = "generated-changelog"
	noChangelogWorkflowLabel              = "no-changelog"
	unreleasedGeneratedChangelogPullTitle = "chore: update CHANGELOG.md [Unreleased] section"
	unreleasedPullRequestActionUpdated    = "updated"
	unreleasedPullRequestActionCreated    = "created"
)

// PullRequestRef summarizes an open GitHub pull used by changelog workflow tests.
type PullRequestRef struct {
	Number int
	URL    string
}

// ChangelogWorkflowREST captures GitHub REST operations used by manageUnreleasedPR /
// refreshReleasePR without wiring env or HTTP in this package.
type ChangelogWorkflowREST interface {
	ListOpenPullRequestsByHead(ctx context.Context, owner, repo, headRef, baseBranch string) ([]PullRequestRef, error)
	CreatePullRequest(ctx context.Context, owner, repo string, title, body, head, base string) (*PullRequestRef, error)
	UpdatePullRequestBody(ctx context.Context, owner, repo string, number int, body string) error
	AddIssueLabels(ctx context.Context, owner, repo string, issueNumber int, labels []string) error
}

// ManageUnreleasedOptions configures ManageUnreleasedPR.
type ManageUnreleasedOptions struct {
	Owner        string
	Repo         string
	BaseBranch   string
	HeadBranch   string
	CompareRange string
	GitHub       ChangelogWorkflowREST
	Now          func() time.Time
}

// ManageUnreleasedResult mirrors manageUnreleasedPR return values plus soft warnings.
type ManageUnreleasedResult struct {
	Warnings []string
	Action   string
	Number   int
	URL      string
}

// BuildUnreleasedPRBody mirrors buildUnreleasedPRBody in changelog-pr-management.js.
func BuildUnreleasedPRBody(compareRange string, generatedDate string) string {
	lines := []string{
		fmt.Sprintf("**Generated:** %s", generatedDate),
		fmt.Sprintf("**Compare range:** `%s`", compareRange),
		"",
		"> This PR is auto-generated by the changelog-generation workflow.",
		"> Re-runs will force-push this branch and overwrite any manual edits.",
		"> Do not make manual edits to the `generated-changelog` branch.",
	}
	return strings.Join(lines, "\n")
}

// ManageUnreleasedPR mirrors manageUnreleasedPR in changelog-pr-management.js.
func ManageUnreleasedPR(ctx context.Context, opts ManageUnreleasedOptions) (ManageUnreleasedResult, error) {
	if opts.GitHub == nil {
		return ManageUnreleasedResult{}, fmt.Errorf("manage unreleased pr: GitHub client required")
	}
	now := opts.Now
	if now == nil {
		now = time.Now
	}
	base := opts.BaseBranch
	if base == "" {
		base = defaultPullRequestBaseBranch
	}
	headBranch := opts.HeadBranch
	if headBranch == "" {
		headBranch = defaultGeneratedChangelogWorkflowHead
	}

	generatedDate := now().UTC().Format("2006-01-02")
	body := BuildUnreleasedPRBody(opts.CompareRange, generatedDate)
	headRef := fmt.Sprintf("%s:%s", opts.Owner, headBranch)

	existing, err := opts.GitHub.ListOpenPullRequestsByHead(ctx, opts.Owner, opts.Repo, headRef, base)
	if err != nil {
		return ManageUnreleasedResult{}, fmt.Errorf("list open pull requests: %w", err)
	}

	if len(existing) > 0 {
		pr := existing[0]
		if err := opts.GitHub.UpdatePullRequestBody(ctx, opts.Owner, opts.Repo, pr.Number, body); err != nil {
			return ManageUnreleasedResult{}, fmt.Errorf("update pull request body: %w", err)
		}
		res := ManageUnreleasedResult{
			Action: unreleasedPullRequestActionUpdated,
			Number: pr.Number,
			URL:    pr.URL,
		}
		appendNoChangelogLabelWarning(ctx, &res.Warnings, opts.GitHub, opts.Owner, opts.Repo, pr.Number)
		return res, nil
	}

	created, err := opts.GitHub.CreatePullRequest(
		ctx,
		opts.Owner,
		opts.Repo,
		unreleasedGeneratedChangelogPullTitle,
		body,
		headBranch,
		base,
	)
	if err != nil {
		return ManageUnreleasedResult{}, fmt.Errorf("create pull request: %w", err)
	}
	res := ManageUnreleasedResult{
		Action: unreleasedPullRequestActionCreated,
		Number: created.Number,
		URL:    created.URL,
	}
	appendNoChangelogLabelWarning(ctx, &res.Warnings, opts.GitHub, opts.Owner, opts.Repo, created.Number)
	return res, nil
}

func appendNoChangelogLabelWarning(
	ctx context.Context,
	warnings *[]string,
	client ChangelogWorkflowREST,
	owner, repo string,
	issueNumber int,
) {
	if err := client.AddIssueLabels(ctx, owner, repo, issueNumber, []string{noChangelogWorkflowLabel}); err != nil {
		// Mirrors addNoChangelogLabel message shape in changelog-pr-management.js warn().
		msg := fmt.Sprintf("Failed to apply %s label to PR #%d: %v", noChangelogWorkflowLabel, issueNumber, err)
		*warnings = append(*warnings, msg)
	}
}
