package securitylist

import (
	"context"
	_ "embed"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
)

//go:embed resource-description.md
var securityListResourceDescription string

func (r *securityListResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: securityListResourceDescription,
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "The unique identifier of the security list (auto-generated by Kibana if not specified).",
				Computed:            true,
				Optional:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"space_id": schema.StringAttribute{
				MarkdownDescription: "An identifier for the space. If space_id is not provided, the default space is used.",
				Optional:            true,
				Computed:            true,
				Default:             stringdefault.StaticString("default"),
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"list_id": schema.StringAttribute{
				MarkdownDescription: "The value list's human-readable identifier.",
				Optional:            true,
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "The name of the security list.",
				Required:            true,
			},
			"description": schema.StringAttribute{
				MarkdownDescription: "Describes the security list.",
				Required:            true,
			},
			"type": schema.StringAttribute{
				MarkdownDescription: "Specifies the Elasticsearch data type of values the list contains. Valid values include: `binary`, `boolean`, `byte`, `date`, `date_nanos`, `date_range`, `double`, `double_range`, `float`, `float_range`, `geo_point`, `geo_shape`, `half_float`, `integer`, `integer_range`, `ip`, `ip_range`, `keyword`, `long`, `long_range`, `shape`, `short`, `text`.",
				Required:            true,
				Validators: []validator.String{
					stringvalidator.OneOf(
						"binary", "boolean", "byte", "date", "date_nanos", "date_range",
						"double", "double_range", "float", "float_range", "geo_point", "geo_shape",
						"half_float", "integer", "integer_range", "ip", "ip_range", "keyword",
						"long", "long_range", "shape", "short", "text",
					),
				},
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"deserializer": schema.StringAttribute{
				MarkdownDescription: "Determines how retrieved list item values are presented. By default, list items are presented using Handlebars expressions based on the type.",
				Optional:            true,
				Computed:            true,
			},
			"serializer": schema.StringAttribute{
				MarkdownDescription: "Determines how uploaded list item values are parsed. By default, list items are parsed using named regex groups based on the type.",
				Optional:            true,
				Computed:            true,
			},
			"meta": schema.StringAttribute{
				MarkdownDescription: "Placeholder for metadata about the value list as JSON string.",
				Optional:            true,
			},
			"version": schema.Int64Attribute{
				MarkdownDescription: "The document version number.",
				Optional:            true,
				Computed:            true,
			},
			"version_id": schema.StringAttribute{
				MarkdownDescription: "The version id, normally returned by the API when the document is retrieved.",
				Computed:            true,
			},
			"immutable": schema.BoolAttribute{
				MarkdownDescription: "Whether the list is immutable.",
				Computed:            true,
			},
			"created_at": schema.StringAttribute{
				MarkdownDescription: "The timestamp of when the list was created.",
				Computed:            true,
			},
			"created_by": schema.StringAttribute{
				MarkdownDescription: "The user who created the list.",
				Computed:            true,
			},
			"updated_at": schema.StringAttribute{
				MarkdownDescription: "The timestamp of when the list was last updated.",
				Computed:            true,
			},
			"updated_by": schema.StringAttribute{
				MarkdownDescription: "The user who last updated the list.",
				Computed:            true,
			},
			"tie_breaker_id": schema.StringAttribute{
				MarkdownDescription: "Field used in search to ensure all containers are sorted and returned correctly.",
				Computed:            true,
			},
		},
	}
}
