// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

package main

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/google/go-github/v89/github"
)

const (
	defaultPullRequestBaseBranch = "main"
	standingPRHeadBranch         = "acceptance-test-version-matrix"
	standingPRTitle              = "chore: update acceptance-test version matrix"
	noChangelogLabel             = "no-changelog"
	standingPRActionCreated      = "created"
	standingPRActionUpdated      = "updated"
	standingPRActionNoop         = "noop"
)

type PullRequestRef struct {
	Number int
	URL    string
}

type StandingPRREST interface {
	ListOpenPullRequestsByHead(ctx context.Context, owner, repo, headRef, baseBranch string) ([]PullRequestRef, error)
	CreatePullRequest(ctx context.Context, owner, repo, title, body, head, base string) (*PullRequestRef, error)
	UpdatePullRequestBody(ctx context.Context, owner, repo string, number int, body string) error
	AddIssueLabels(ctx context.Context, owner, repo string, issueNumber int, labels []string) error
}

type ManageStandingOptions struct {
	Changed    bool
	Owner      string
	Repo       string
	BaseBranch string
	HeadBranch string
	GitHub     StandingPRREST
	Now        func() time.Time
}

type ManageStandingResult struct {
	Warnings []string
	Action   string
	Number   int
	URL      string
}

func BuildStandingPRBody(generatedDate string) string {
	lines := []string{
		fmt.Sprintf("**Generated:** %s", generatedDate),
		"",
		"Merging this pull request makes the default branch's pinned acceptance-test version list",
		"equal the full computed list. This is all-or-nothing: a newly-red GA version holds the",
		"whole delta rather than being silently dropped.",
		"",
		"> This PR is auto-generated by the version-matrix-generation workflow.",
		"> Re-runs will force-push this branch and overwrite any manual edits.",
		"> Do not make manual edits to the `acceptance-test-version-matrix` branch.",
	}
	return strings.Join(lines, "\n")
}

func ManageStandingPR(ctx context.Context, opts ManageStandingOptions) (ManageStandingResult, error) {
	if !opts.Changed {
		return ManageStandingResult{Action: standingPRActionNoop}, nil
	}

	now := opts.Now
	if now == nil {
		now = time.Now
	}
	base := opts.BaseBranch
	if base == "" {
		base = defaultPullRequestBaseBranch
	}
	headBranch := opts.HeadBranch
	if headBranch == "" {
		headBranch = standingPRHeadBranch
	}

	if opts.GitHub == nil {
		return ManageStandingResult{}, fmt.Errorf("manage standing pr: GitHub client required")
	}

	body := BuildStandingPRBody(now().UTC().Format("2006-01-02"))
	headRef := fmt.Sprintf("%s:%s", opts.Owner, headBranch)

	existing, err := opts.GitHub.ListOpenPullRequestsByHead(ctx, opts.Owner, opts.Repo, headRef, base)
	if err != nil {
		return ManageStandingResult{}, fmt.Errorf("list open pull requests: %w", err)
	}

	if len(existing) > 0 {
		pr := existing[0]
		if err := opts.GitHub.UpdatePullRequestBody(ctx, opts.Owner, opts.Repo, pr.Number, body); err != nil {
			return ManageStandingResult{}, fmt.Errorf("update pull request body: %w", err)
		}
		res := ManageStandingResult{
			Action: standingPRActionUpdated,
			Number: pr.Number,
			URL:    pr.URL,
		}
		appendNoChangelogLabelWarning(ctx, &res.Warnings, opts.GitHub, opts.Owner, opts.Repo, pr.Number)
		return res, nil
	}

	created, err := opts.GitHub.CreatePullRequest(
		ctx,
		opts.Owner,
		opts.Repo,
		standingPRTitle,
		body,
		headBranch,
		base,
	)
	if err != nil {
		return ManageStandingResult{}, fmt.Errorf("create pull request: %w", err)
	}
	res := ManageStandingResult{
		Action: standingPRActionCreated,
		Number: created.Number,
		URL:    created.URL,
	}
	appendNoChangelogLabelWarning(ctx, &res.Warnings, opts.GitHub, opts.Owner, opts.Repo, created.Number)
	return res, nil
}

type githubStandingREST struct {
	client *github.Client
}

func (g *githubStandingREST) requireClient() error {
	if g == nil || g.client == nil {
		return fmt.Errorf("github client required")
	}
	return nil
}

func (g *githubStandingREST) ListOpenPullRequestsByHead(ctx context.Context, owner, repo, headRef, baseBranch string) ([]PullRequestRef, error) {
	if err := g.requireClient(); err != nil {
		return nil, err
	}
	pulls, _, err := g.client.PullRequests.List(ctx, owner, repo, &github.PullRequestListOptions{
		State: "open",
		Head:  headRef,
		Base:  baseBranch,
	})
	if err != nil {
		return nil, fmt.Errorf("list pull requests: %w", err)
	}
	out := make([]PullRequestRef, 0, len(pulls))
	for _, pr := range pulls {
		out = append(out, PullRequestRef{Number: pr.GetNumber(), URL: pr.GetHTMLURL()})
	}
	return out, nil
}

func (g *githubStandingREST) CreatePullRequest(ctx context.Context, owner, repo, title, body, head, base string) (*PullRequestRef, error) {
	if err := g.requireClient(); err != nil {
		return nil, err
	}
	titleCopy, headCopy, baseCopy, bodyCopy := title, head, base, body
	pr, _, err := g.client.PullRequests.Create(ctx, owner, repo, &github.NewPullRequest{
		Title: &titleCopy,
		Head:  &headCopy,
		Base:  &baseCopy,
		Body:  &bodyCopy,
	})
	if err != nil {
		return nil, fmt.Errorf("create pull request: %w", err)
	}
	return &PullRequestRef{Number: pr.GetNumber(), URL: pr.GetHTMLURL()}, nil
}

func (g *githubStandingREST) UpdatePullRequestBody(ctx context.Context, owner, repo string, number int, body string) error {
	if err := g.requireClient(); err != nil {
		return err
	}
	bodyCopy := body
	if _, _, err := g.client.PullRequests.Edit(ctx, owner, repo, number, &github.PullRequest{Body: &bodyCopy}); err != nil {
		return fmt.Errorf("edit pull request body: %w", err)
	}
	return nil
}

func (g *githubStandingREST) AddIssueLabels(ctx context.Context, owner, repo string, issueNumber int, labels []string) error {
	if err := g.requireClient(); err != nil {
		return err
	}
	if _, _, err := g.client.Issues.AddLabelsToIssue(ctx, owner, repo, issueNumber, labels); err != nil {
		return fmt.Errorf("add labels to pull request #%d: %w", issueNumber, err)
	}
	return nil
}

func appendNoChangelogLabelWarning(
	ctx context.Context,
	warnings *[]string,
	client StandingPRREST,
	owner, repo string,
	issueNumber int,
) {
	if err := client.AddIssueLabels(ctx, owner, repo, issueNumber, []string{noChangelogLabel}); err != nil {
		msg := fmt.Sprintf("Failed to apply %s label to PR #%d: %v", noChangelogLabel, issueNumber, err)
		*warnings = append(*warnings, msg)
	}
}
