name: New Stack functionality
description: Add support for new Stack functionality
title: "[FEATURE] <title>"
labels: ["Feature", "Stack Led"]
body:
- type: input
  attributes:
    label: Name of the resource
    description: What is the name of the resource you are adding or extending?
    placeholder: "e.g elasticstack_elasticsearch_ml_datafeed"
- type: textarea
  attributes:
    label: Describe new functionality
    description: A concise description of the new functionality to add. 
    placeholder: |
      If you're extending an existing resource, describe any new fields, or changes to existing fields
      e.g:
        Add support for `query` field to the Machine Learning Datafeed resource.

      If you're adding an entirely new resource, describe the resource and its purpose. 
      Make sure to include links to relevant API documentation.
      e.g 
        Add a new Machine Learning Datafeed resource to manage datafeeds for ML jobs.
        API docs:
          - Create: https://www.elastic.co/docs/api/doc/elasticsearch/operation/operation-ml-put-datafeed
          - Get: https://www.elastic.co/docs/api/doc/elasticsearch/operation/operation-ml-get-datafeeds
          - Delete: https://www.elastic.co/docs/api/doc/elasticsearch/operation/operation-ml-delete-datafeed
  validations:
    required: true
- type: input
  attributes:
    label: Version Introduced
    description: What version of the Stack was this functionality introduced in?
    placeholder: "e.g 9.2.0"
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    placeholder: |
      Links? References? Anything that will give us more context about the functionality you're adding!

      e.g:
        - Links to issues/PRs where this was added in Elasticsearch/Kibana etc.
        - Links to any relevant documentation. 
        - Describe any dependencies or relationships to other resources (e.g an ML datafeed is linked to an anomaly detection job).
        - Describe any edge cases that should be covered in acceptance testing. 
  validations:
    required: false
