package anomaly_detector

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *anomalyDetectorResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Creates or updates an Elasticsearch machine learning job.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description: "Internal identifier of the resource.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"job_id": schema.StringAttribute{
				Description: "The ID of the job to create.",
				Required:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"description": schema.StringAttribute{
				Description: "A description of the job.",
				Optional:    true,
			},
			"groups": schema.ListAttribute{
				Description: "A list of job groups. A job can belong to no groups or many.",
				ElementType: types.StringType,
				Optional:    true,
			},
			"analysis_config": schema.SingleNestedAttribute{
				Description: "The analysis configuration, which specifies how to analyze the data.",
				Required:    true,
				Attributes: map[string]schema.Attribute{
					"bucket_span": schema.StringAttribute{
						Description: "The span of the analysis time bucket.",
						Required:    true,
					},
					"detectors": schema.ListNestedAttribute{
						Description: "An array of detector objects, which define the statistical analysis that will be performed.",
						Required:    true,
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"function": schema.StringAttribute{
									Description: "The analysis function that is used. For example, count, rare, mean, median, min, max, sum, lat_long, time_of_day, time_of_week, metric, text_field.",
									Required:    true,
								},
								"field_name": schema.StringAttribute{
									Description: "The field that the detector analyzes.",
									Optional:    true,
								},
								"by_field_name": schema.StringAttribute{
									Description: "The field used to split the data. In particular, this property is used for analyzing the splits with respect to the history of all splits. Refer to performing multifactor analysis.",
									Optional:    true,
								},
								"partition_field_name": schema.StringAttribute{
									Description: "The field used to segment the analysis. When you use this property, you have completely independent baselines for each value of this field.",
									Optional:    true,
								},
							},
						},
					},
					"influencers": schema.ListAttribute{
						Description: "A list of strings that influence the anomaly results.",
						ElementType: types.StringType,
						Optional:    true,
					},
				},
			},
			"data_description": schema.SingleNestedAttribute{
				Description: "The data description, which specifies how to interpret the data.",
				Required:    true,
				Attributes: map[string]schema.Attribute{
					"time_field": schema.StringAttribute{
						Description: "The name of the field that contains the timestamp.",
						Required:    true,
					},
				},
			},
			"model_plot_config": schema.SingleNestedAttribute{
				Description: "This advanced configuration option stores model information along with the results.",
				Optional:    true,
				Attributes: map[string]schema.Attribute{
					"enabled": schema.BoolAttribute{
						Description: "If true, model plot information is stored along with the results. This adds overhead to the performance of the system and is not generally needed.",
						Optional:    true,
					},
				},
			},
			"results_index_name": schema.StringAttribute{
				Description: "The name of the index in which to store the machine learning results.",
				Optional:    true,
				Computed:    true, // It can be auto-generated by ES
			},
		},
	}
}
