// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

package kibana

import (
	"context"
	"regexp"

	"github.com/elastic/terraform-provider-elasticstack/generated/kbapi"
	"github.com/elastic/terraform-provider-elasticstack/internal/clients"
	"github.com/elastic/terraform-provider-elasticstack/internal/clients/kibanaoapi"
	providerSchema "github.com/elastic/terraform-provider-elasticstack/internal/schema"
	"github.com/hashicorp/go-version"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
)

var spaceSolutionMinVersion = version.Must(version.NewVersion("8.16.0"))

func ResourceSpace() *schema.Resource {
	apikeySchema := map[string]*schema.Schema{
		"id": {
			Description: "Internal identifier of the resource.",
			Type:        schema.TypeString,
			Computed:    true,
		},
		"space_id": {
			Description:  "The space ID that is part of the Kibana URL when inside the space.",
			Type:         schema.TypeString,
			Required:     true,
			ForceNew:     true,
			ValidateFunc: validation.StringMatch(regexp.MustCompile("^[a-z0-9_-]+$"), "must only contain lowercase letters, numbers, hyphens, and underscores"),
		},
		"name": {
			Description: "The display name for the space.",
			Type:        schema.TypeString,
			Required:    true,
		},
		"description": {
			Description: "The description for the space.",
			Type:        schema.TypeString,
			Optional:    true,
		},
		"disabled_features": {
			Description: "The list of disabled features for the space. To get a list of available feature IDs, use the Features API (https://www.elastic.co/guide/en/kibana/master/features-api-get.html).",
			Type:        schema.TypeSet,
			Optional:    true,
			Computed:    true,
			Elem: &schema.Schema{
				Type: schema.TypeString,
			},
		},
		"initials": {
			Description:  "The initials shown in the space avatar. By default, the initials are automatically generated from the space name. Initials must be 1 or 2 characters.",
			Type:         schema.TypeString,
			Computed:     true, // If not provided, a value is autogenerated
			Optional:     true,
			ValidateFunc: validation.StringLenBetween(1, 2),
		},
		"color": {
			Description: "The hexadecimal color code used in the space avatar. By default, the color is automatically generated from the space name.",
			Type:        schema.TypeString,
			Computed:    true, // If not provided, a value is autogenerated
			Optional:    true,
		},
		"image_url": {
			Description:  "The data-URL encoded image to display in the space avatar.",
			Type:         schema.TypeString,
			Optional:     true,
			ValidateFunc: validation.StringMatch(regexp.MustCompile("^data:image/"), "must be a valid data-URL encoded image"),
		},
		"solution": {
			Description:  "The solution view for the space. Valid options are `security`, `oblt`, `es`, or `classic`.",
			Type:         schema.TypeString,
			Optional:     true,
			Computed:     true,
			ValidateFunc: validation.StringInSlice([]string{"security", "oblt", "es", "classic"}, false),
		},
		"kibana_connection": providerSchema.GetKibanaEntityConnectionSchema(),
	}

	return &schema.Resource{
		Description: "Creates a Kibana space. See the [spaces API documentation](https://www.elastic.co/guide/en/kibana/master/spaces-api-post.html) for more details.",

		CreateContext: resourceSpaceUpsert,
		UpdateContext: resourceSpaceUpsert,
		ReadContext:   resourceSpaceRead,
		DeleteContext: resourceSpaceDelete,

		Importer: &schema.ResourceImporter{
			StateContext: schema.ImportStatePassthroughContext,
		},

		Schema: apikeySchema,
	}
}

func resourceSpaceUpsert(ctx context.Context, d *schema.ResourceData, meta any) diag.Diagnostics {
	factory, diags := clients.ConvertMetaToFactory(meta)
	if diags.HasError() {
		return diags
	}
	client, diags := factory.GetKibanaClientFromSDK(d)
	if diags.HasError() {
		return diags
	}

	// Check version compatibility for solution field
	if solution, ok := d.GetOk("solution"); ok && solution.(string) != "" {
		serverVersion, diags := client.ServerVersion(ctx)
		if diags.HasError() {
			return diags
		}

		if !serverVersion.GreaterThanOrEqual(spaceSolutionMinVersion) {
			return diag.Errorf("solution field is not supported in this version of the Elastic Stack. Solution field requires %s or higher", spaceSolutionMinVersion)
		}
	}

	oapiClient, err := client.GetKibanaOapiClient()
	if err != nil {
		return diag.FromErr(err)
	}

	spaceID := d.Get("space_id").(string)
	name := d.Get("name").(string)

	var description *string
	if v, ok := d.GetOk("description"); ok {
		s := v.(string)
		description = &s
	}

	features := make([]string, 0)
	if v, ok := d.GetOk("disabled_features"); ok {
		p := v.(*schema.Set)
		for _, e := range p.List() {
			features = append(features, e.(string))
		}
	}

	var initials *string
	if v, ok := d.GetOk("initials"); ok {
		s := v.(string)
		initials = &s
	}

	var color *string
	if v, ok := d.GetOk("color"); ok {
		s := v.(string)
		color = &s
	}

	var imageURL *string
	if v, ok := d.GetOk("image_url"); ok {
		s := v.(string)
		imageURL = &s
	}

	var spaceResponse *kbapi.SpaceResponse

	if d.IsNewResource() {
		body := kbapi.PostSpacesSpaceJSONRequestBody{
			Id:               spaceID,
			Name:             name,
			Description:      description,
			DisabledFeatures: &features,
			Initials:         initials,
			Color:            color,
			ImageUrl:         imageURL,
		}
		if v, ok := d.GetOk("solution"); ok {
			s := kbapi.PostSpacesSpaceJSONBodySolution(v.(string))
			body.Solution = &s
		}
		spaceResponse, diags = kibanaoapi.CreateSpace(ctx, oapiClient, body)
		if diags.HasError() {
			return diags
		}
	} else {
		body := kbapi.PutSpacesSpaceIdJSONRequestBody{
			Id:               spaceID,
			Name:             name,
			Description:      description,
			DisabledFeatures: &features,
			Initials:         initials,
			Color:            color,
			ImageUrl:         imageURL,
		}
		if v, ok := d.GetOk("solution"); ok {
			s := kbapi.PutSpacesSpaceIdJSONBodySolution(v.(string))
			body.Solution = &s
		}
		spaceResponse, diags = kibanaoapi.UpdateSpace(ctx, oapiClient, spaceID, body)
		if diags.HasError() {
			return diags
		}
	}

	d.SetId(spaceResponse.Id)

	return resourceSpaceRead(ctx, d, meta)
}

func resourceSpaceRead(ctx context.Context, d *schema.ResourceData, meta any) diag.Diagnostics {
	factory, diags := clients.ConvertMetaToFactory(meta)
	if diags.HasError() {
		return diags
	}
	client, diags := factory.GetKibanaClientFromSDK(d)
	if diags.HasError() {
		return diags
	}
	id := d.Id()
	if compID, diags := clients.CompositeIDFromStr(id); diags == nil {
		id = compID.ResourceID
	}

	oapiClient, err := client.GetKibanaOapiClient()
	if err != nil {
		return diag.FromErr(err)
	}

	space, sdkDiags := kibanaoapi.GetSpaceSDK(ctx, oapiClient, id)
	if sdkDiags.HasError() {
		return sdkDiags
	}
	if space == nil {
		d.SetId("")
		return diags
	}

	// set the fields
	if err := d.Set("space_id", space.Id); err != nil {
		return diag.FromErr(err)
	}
	if err := d.Set("name", space.Name); err != nil {
		return diag.FromErr(err)
	}
	if space.Description != nil {
		if err := d.Set("description", *space.Description); err != nil {
			return diag.FromErr(err)
		}
	} else {
		if err := d.Set("description", ""); err != nil {
			return diag.FromErr(err)
		}
	}
	disabledFeatures := []string{}
	if space.DisabledFeatures != nil {
		disabledFeatures = *space.DisabledFeatures
	}
	if err := d.Set("disabled_features", disabledFeatures); err != nil {
		return diag.FromErr(err)
	}
	initials := ""
	if space.Initials != nil {
		initials = *space.Initials
	}
	if err := d.Set("initials", initials); err != nil {
		return diag.FromErr(err)
	}
	color := ""
	if space.Color != nil {
		color = *space.Color
	}
	if err := d.Set("color", color); err != nil {
		return diag.FromErr(err)
	}
	if space.Solution != nil {
		if err := d.Set("solution", *space.Solution); err != nil {
			return diag.FromErr(err)
		}
	} else {
		if err := d.Set("solution", ""); err != nil {
			return diag.FromErr(err)
		}
	}
	// image_url is intentionally not populated from API read (preserved behavior)

	return diags
}

func resourceSpaceDelete(ctx context.Context, d *schema.ResourceData, meta any) diag.Diagnostics {
	factory, diags := clients.ConvertMetaToFactory(meta)
	if diags.HasError() {
		return diags
	}
	client, diags := factory.GetKibanaClientFromSDK(d)
	if diags.HasError() {
		return diags
	}
	id := d.Id()
	if compID, diags := clients.CompositeIDFromStr(id); diags == nil {
		id = compID.ResourceID
	}

	oapiClient, err := client.GetKibanaOapiClient()
	if err != nil {
		return diag.FromErr(err)
	}

	if sdkDiags := kibanaoapi.DeleteSpace(ctx, oapiClient, id); sdkDiags.HasError() {
		return sdkDiags
	}

	d.SetId("")
	return diags
}
