// Code generated by MockGen. DO NOT EDIT.
// Source: ./alerting.go
//
// Generated by this command:
//
//	mockgen -destination=./alerting_mocks.go -package=kibana -source ./alerting.go ApiClient
//

// Package kibana is a generated GoMock package.
package kibana

import (
	reflect "reflect"

	kibana_oapi "github.com/elastic/terraform-provider-elasticstack/internal/clients/kibana_oapi"
	gomock "go.uber.org/mock/gomock"
)

// MockApiClient is a mock of ApiClient interface.
type MockApiClient struct {
	ctrl     *gomock.Controller
	recorder *MockApiClientMockRecorder
	isgomock struct{}
}

// MockApiClientMockRecorder is the mock recorder for MockApiClient.
type MockApiClientMockRecorder struct {
	mock *MockApiClient
}

// NewMockApiClient creates a new mock instance.
func NewMockApiClient(ctrl *gomock.Controller) *MockApiClient {
	mock := &MockApiClient{ctrl: ctrl}
	mock.recorder = &MockApiClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApiClient) EXPECT() *MockApiClientMockRecorder {
	return m.recorder
}

// GetKibanaOapiClient mocks base method.
func (m *MockApiClient) GetKibanaOapiClient() (*kibana_oapi.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKibanaOapiClient")
	ret0, _ := ret[0].(*kibana_oapi.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKibanaOapiClient indicates an expected call of GetKibanaOapiClient.
func (mr *MockApiClientMockRecorder) GetKibanaOapiClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKibanaOapiClient", reflect.TypeOf((*MockApiClient)(nil).GetKibanaOapiClient))
}
