// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

package kibana

import (
	"context"
	"fmt"

	"github.com/elastic/terraform-provider-elasticstack/generated/kbapi"
	"github.com/elastic/terraform-provider-elasticstack/internal/clients"
	kibanaoapi "github.com/elastic/terraform-provider-elasticstack/internal/clients/kibanaoapi"
	"github.com/elastic/terraform-provider-elasticstack/internal/models"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
)

func GetSlo(ctx context.Context, apiClient *clients.KibanaScopedClient, id, spaceID string) (*models.Slo, diag.Diagnostics) {
	client, err := apiClient.GetKibanaOapiClient()
	if err != nil {
		return nil, diag.FromErr(err)
	}

	res, fwDiags := kibanaoapi.GetSlo(ctx, client, spaceID, id)
	if fwDiags.HasError() {
		var diags diag.Diagnostics
		for _, d := range fwDiags {
			diags = append(diags, diag.Diagnostic{
				Severity: diag.Error,
				Summary:  d.Summary(),
				Detail:   d.Detail(),
			})
		}
		return nil, diags
	}

	return sloResponseToModel(spaceID, res), nil
}

func DeleteSlo(ctx context.Context, apiClient *clients.KibanaScopedClient, sloID string, spaceID string) diag.Diagnostics {
	client, err := apiClient.GetKibanaOapiClient()
	if err != nil {
		return diag.FromErr(err)
	}

	fwDiags := kibanaoapi.DeleteSlo(ctx, client, spaceID, sloID)
	if fwDiags.HasError() {
		var diags diag.Diagnostics
		for _, d := range fwDiags {
			diags = append(diags, diag.Diagnostic{
				Severity: diag.Error,
				Summary:  d.Summary(),
				Detail:   d.Detail(),
			})
		}
		return diags
	}

	return nil
}

func UpdateSlo(ctx context.Context, apiClient *clients.KibanaScopedClient, s models.Slo, supportsGroupByList bool) (*models.Slo, diag.Diagnostics) {
	client, err := apiClient.GetKibanaOapiClient()
	if err != nil {
		return nil, diag.FromErr(err)
	}

	indicator, convErr := responseIndicatorToUpdateIndicator(s.Indicator)
	if convErr != nil {
		return nil, diag.FromErr(convErr)
	}

	groupBy := transformGroupBy(s.GroupBy, supportsGroupByList)
	reqModel := kbapi.SLOsUpdateSloRequest{
		Name:            &s.Name,
		Description:     &s.Description,
		Indicator:       &indicator,
		TimeWindow:      &s.TimeWindow,
		BudgetingMethod: &s.BudgetingMethod,
		Objective:       &s.Objective,
		Settings:        s.Settings,
		GroupBy:         groupBy,
		Tags:            tagsToPtr(s.Tags),
	}

	fwDiags := kibanaoapi.UpdateSlo(ctx, client, s.SpaceID, s.SloID, reqModel)
	if fwDiags.HasError() {
		var diags diag.Diagnostics
		for _, d := range fwDiags {
			diags = append(diags, diag.Diagnostic{
				Severity: diag.Error,
				Summary:  d.Summary(),
				Detail:   d.Detail(),
			})
		}
		return nil, diags
	}

	return &s, diag.Diagnostics{}
}

func CreateSlo(ctx context.Context, apiClient *clients.KibanaScopedClient, s models.Slo, supportsGroupByList bool) (*models.Slo, diag.Diagnostics) {
	client, err := apiClient.GetKibanaOapiClient()
	if err != nil {
		return nil, diag.FromErr(err)
	}

	indicator, convErr := responseIndicatorToCreateIndicator(s.Indicator)
	if convErr != nil {
		return nil, diag.FromErr(convErr)
	}

	groupBy := transformGroupBy(s.GroupBy, supportsGroupByList)
	reqModel := kbapi.SLOsCreateSloRequest{
		Name:            s.Name,
		Description:     s.Description,
		Indicator:       indicator,
		TimeWindow:      s.TimeWindow,
		BudgetingMethod: s.BudgetingMethod,
		Objective:       s.Objective,
		Settings:        s.Settings,
		GroupBy:         groupBy,
		Tags:            tagsToPtr(s.Tags),
	}

	// Explicitly set SLO object id if provided, otherwise use the autogenerated ID from the Kibana API response.
	if s.SloID != "" {
		reqModel.Id = &s.SloID
	}

	res, fwDiags := kibanaoapi.CreateSlo(ctx, client, s.SpaceID, reqModel)
	if fwDiags.HasError() {
		var diags diag.Diagnostics
		for _, d := range fwDiags {
			diags = append(diags, diag.Diagnostic{
				Severity: diag.Error,
				Summary:  d.Summary(),
				Detail:   d.Detail(),
			})
		}
		return nil, diags
	}

	s.SloID = res.Id
	return &s, diag.Diagnostics{}
}

// responseIndicatorToCreateIndicator converts the response indicator union type to the create request
// indicator union type. Both are discriminated JSON unions sharing the same underlying indicator structs.
func responseIndicatorToCreateIndicator(s kbapi.SLOsSloWithSummaryResponse_Indicator) (kbapi.SLOsCreateSloRequest_Indicator, error) {
	discriminator, err := s.Discriminator()
	if err != nil {
		return kbapi.SLOsCreateSloRequest_Indicator{}, fmt.Errorf("unknown indicator type: %w", err)
	}

	var ret kbapi.SLOsCreateSloRequest_Indicator
	switch discriminator {
	case "sli.apm.transactionErrorRate":
		ind, err := s.AsSLOsIndicatorPropertiesApmAvailability()
		if err != nil {
			return ret, err
		}
		err = ret.FromSLOsIndicatorPropertiesApmAvailability(ind)
		return ret, err
	case "sli.apm.transactionDuration":
		ind, err := s.AsSLOsIndicatorPropertiesApmLatency()
		if err != nil {
			return ret, err
		}
		err = ret.FromSLOsIndicatorPropertiesApmLatency(ind)
		return ret, err
	case "sli.kql.custom":
		ind, err := s.AsSLOsIndicatorPropertiesCustomKql()
		if err != nil {
			return ret, err
		}
		err = ret.FromSLOsIndicatorPropertiesCustomKql(ind)
		return ret, err
	case "sli.metric.custom":
		ind, err := s.AsSLOsIndicatorPropertiesCustomMetric()
		if err != nil {
			return ret, err
		}
		err = ret.FromSLOsIndicatorPropertiesCustomMetric(ind)
		return ret, err
	case "sli.histogram.custom":
		ind, err := s.AsSLOsIndicatorPropertiesHistogram()
		if err != nil {
			return ret, err
		}
		err = ret.FromSLOsIndicatorPropertiesHistogram(ind)
		return ret, err
	case "sli.metric.timeslice":
		ind, err := s.AsSLOsIndicatorPropertiesTimesliceMetric()
		if err != nil {
			return ret, err
		}
		err = ret.FromSLOsIndicatorPropertiesTimesliceMetric(ind)
		return ret, err
	default:
		return ret, fmt.Errorf("unknown indicator discriminator: %s", discriminator)
	}
}

// responseIndicatorToUpdateIndicator converts the response indicator union type to the update request
// indicator union type.
func responseIndicatorToUpdateIndicator(s kbapi.SLOsSloWithSummaryResponse_Indicator) (kbapi.SLOsUpdateSloRequest_Indicator, error) {
	discriminator, err := s.Discriminator()
	if err != nil {
		return kbapi.SLOsUpdateSloRequest_Indicator{}, fmt.Errorf("unknown indicator type: %w", err)
	}

	var ret kbapi.SLOsUpdateSloRequest_Indicator
	switch discriminator {
	case "sli.apm.transactionErrorRate":
		ind, err := s.AsSLOsIndicatorPropertiesApmAvailability()
		if err != nil {
			return ret, err
		}
		err = ret.FromSLOsIndicatorPropertiesApmAvailability(ind)
		return ret, err
	case "sli.apm.transactionDuration":
		ind, err := s.AsSLOsIndicatorPropertiesApmLatency()
		if err != nil {
			return ret, err
		}
		err = ret.FromSLOsIndicatorPropertiesApmLatency(ind)
		return ret, err
	case "sli.kql.custom":
		ind, err := s.AsSLOsIndicatorPropertiesCustomKql()
		if err != nil {
			return ret, err
		}
		err = ret.FromSLOsIndicatorPropertiesCustomKql(ind)
		return ret, err
	case "sli.metric.custom":
		ind, err := s.AsSLOsIndicatorPropertiesCustomMetric()
		if err != nil {
			return ret, err
		}
		err = ret.FromSLOsIndicatorPropertiesCustomMetric(ind)
		return ret, err
	case "sli.histogram.custom":
		ind, err := s.AsSLOsIndicatorPropertiesHistogram()
		if err != nil {
			return ret, err
		}
		err = ret.FromSLOsIndicatorPropertiesHistogram(ind)
		return ret, err
	case "sli.metric.timeslice":
		ind, err := s.AsSLOsIndicatorPropertiesTimesliceMetric()
		if err != nil {
			return ret, err
		}
		err = ret.FromSLOsIndicatorPropertiesTimesliceMetric(ind)
		return ret, err
	default:
		return ret, fmt.Errorf("unknown indicator discriminator: %s", discriminator)
	}
}

func sloResponseToModel(spaceID string, res *kbapi.SLOsSloWithSummaryResponse) *models.Slo {
	if res == nil {
		return nil
	}

	return &models.Slo{
		SloID:           res.Id,
		SpaceID:         spaceID,
		Name:            res.Name,
		Description:     res.Description,
		BudgetingMethod: res.BudgetingMethod,
		Indicator:       res.Indicator,
		TimeWindow:      res.TimeWindow,
		Objective:       res.Objective,
		Settings:        &res.Settings,
		GroupBy:         transformGroupByFromResponse(res.GroupBy),
		Tags:            res.Tags,
	}
}

func transformGroupBy(groupBy []string, supportsGroupByList bool) *kbapi.SLOsGroupBy {
	if groupBy == nil {
		return nil
	}

	var gb kbapi.SLOsGroupBy
	if supportsGroupByList {
		if err := gb.FromSLOsGroupBy1(groupBy); err != nil {
			return nil
		}
		return &gb
	}

	if len(groupBy) == 0 {
		return nil
	}

	if err := gb.FromSLOsGroupBy0(groupBy[0]); err != nil {
		return nil
	}
	return &gb
}

func transformGroupByFromResponse(groupBy kbapi.SLOsGroupBy) []string {
	// Try string first
	if s, err := groupBy.AsSLOsGroupBy0(); err == nil {
		return []string{s}
	}

	// Try array
	if arr, err := groupBy.AsSLOsGroupBy1(); err == nil {
		return arr
	}

	return nil
}

func tagsToPtr(tags []string) *[]string {
	if tags == nil {
		return nil
	}
	return &tags
}
