package exception_list

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *exceptionListResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Creates and manages Kibana exception lists (exception containers). Exception lists are containers for related exceptions that can be associated with security detection rules.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description: "The unique identifier of the exception list. This is generated by Kibana.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"space_id": schema.StringAttribute{
				Description: "The Kibana space ID where the exception list exists. Defaults to 'default'.",
				Optional:    true,
				Computed:    true,
				Default:     stringdefault.StaticString("default"),
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"list_id": schema.StringAttribute{
				Description: "The human-readable unique identifier for the exception list (e.g., 'my-exception-list'). If not provided, Kibana will generate one.",
				Optional:    true,
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				Description: "The name of the exception list.",
				Required:    true,
			},
			"description": schema.StringAttribute{
				Description: "A description of the exception list.",
				Required:    true,
			},
			"type": schema.StringAttribute{
				Description: "The type of exception list. Valid values are: 'detection', 'rule_default', 'endpoint', 'endpoint_trusted_apps', 'endpoint_events', 'endpoint_host_isolation_exceptions', 'endpoint_blocklists'.",
				Required:    true,
				Validators: []validator.String{
					stringvalidator.OneOf(
						"detection",
						"rule_default",
						"endpoint",
						"endpoint_trusted_apps",
						"endpoint_events",
						"endpoint_host_isolation_exceptions",
						"endpoint_blocklists",
					),
				},
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"namespace_type": schema.StringAttribute{
				Description: "Determines whether the exception list is available in all Kibana spaces or just the space in which it is created. Valid values are: 'single' (only available in the space where created) or 'agnostic' (available in all spaces). Defaults to 'single'.",
				Optional:    true,
				Computed:    true,
				Default:     stringdefault.StaticString("single"),
				Validators: []validator.String{
					stringvalidator.OneOf("single", "agnostic"),
				},
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"os_types": schema.ListAttribute{
				Description: "Array of operating system types for which the exception list applies. Valid values include: 'linux', 'macos', 'windows'.",
				Optional:    true,
				Computed:    true,
				ElementType: types.StringType,
				Default:     listdefault.StaticValue(types.ListNull(types.StringType)),
				ElementValidators: []validator.String{
					stringvalidator.OneOf("linux", "macos", "windows"),
				},
			},
			"tags": schema.ListAttribute{
				Description: "Array of tags to help categorize the exception list.",
				Optional:    true,
				Computed:    true,
				ElementType: types.StringType,
				Default:     listdefault.StaticValue(types.ListNull(types.StringType)),
			},
			"meta": schema.SingleNestedAttribute{
				Description: "Optional metadata about the exception list.",
				Optional:    true,
				Computed:    true,
				Attributes: map[string]schema.Attribute{
					"additional_properties": schema.MapAttribute{
						Description: "Additional metadata properties as key-value pairs.",
						Optional:    true,
						Computed:    true,
						ElementType: types.StringType,
					},
				},
				Default: objectdefault.StaticValue(types.ObjectNull(metaModel{}.attrTypes())),
			},
			"version": schema.Int64Attribute{
				Description: "The version of the exception list.",
				Computed:    true,
			},
		},
	}
}
