package exception_list

import (
	"context"
	_ "embed"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

//go:embed resource-description.md
var exceptionListResourceDescription string

func (r *ExceptionListResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: exceptionListResourceDescription,
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "The unique identifier of the exception list (auto-generated by Kibana).",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"list_id": schema.StringAttribute{
				MarkdownDescription: "The exception list's human readable string identifier.",
				Required:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "The name of the exception list.",
				Required:            true,
			},
			"description": schema.StringAttribute{
				MarkdownDescription: "Describes the exception list.",
				Required:            true,
			},
			"type": schema.StringAttribute{
				MarkdownDescription: "The type of exception list. Can be one of: `detection`, `endpoint`, `endpoint_trusted_apps`, `endpoint_events`, `endpoint_host_isolation_exceptions`, `endpoint_blocklists`.",
				Required:            true,
				Validators: []validator.String{
					stringvalidator.OneOf(
						"detection",
						"endpoint",
						"endpoint_trusted_apps",
						"endpoint_events",
						"endpoint_host_isolation_exceptions",
						"endpoint_blocklists",
					),
				},
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"namespace_type": schema.StringAttribute{
				MarkdownDescription: "Determines whether the exception list is available in all Kibana spaces or just the space in which it is created. Can be `single` (default) or `agnostic`.",
				Optional:            true,
				Computed:            true,
				Default:             stringdefault.StaticString("single"),
				Validators: []validator.String{
					stringvalidator.OneOf("single", "agnostic"),
				},
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"os_types": schema.ListAttribute{
				MarkdownDescription: "Array of OS types for which the exceptions apply. Valid values: `linux`, `macos`, `windows`.",
				Optional:            true,
				ElementType:         types.StringType,
			},
			"tags": schema.ListAttribute{
				MarkdownDescription: "String array containing words and phrases to help categorize exception containers.",
				Optional:            true,
				ElementType:         types.StringType,
			},
			"meta": schema.StringAttribute{
				MarkdownDescription: "Placeholder for metadata about the list container as JSON string.",
				Optional:            true,
			},
			"created_at": schema.StringAttribute{
				MarkdownDescription: "The timestamp of when the exception list was created.",
				Computed:            true,
			},
			"created_by": schema.StringAttribute{
				MarkdownDescription: "The user who created the exception list.",
				Computed:            true,
			},
			"updated_at": schema.StringAttribute{
				MarkdownDescription: "The timestamp of when the exception list was last updated.",
				Computed:            true,
			},
			"updated_by": schema.StringAttribute{
				MarkdownDescription: "The user who last updated the exception list.",
				Computed:            true,
			},
			"immutable": schema.BoolAttribute{
				MarkdownDescription: "Whether the exception list is immutable.",
				Computed:            true,
			},
			"tie_breaker_id": schema.StringAttribute{
				MarkdownDescription: "Field used in search to ensure all containers are sorted and returned correctly.",
				Computed:            true,
			},
		},
	}
}
