// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

package slo

import (
	"context"

	"github.com/elastic/terraform-provider-elasticstack/generated/kbapi"
	"github.com/elastic/terraform-provider-elasticstack/internal/clients"
	kibanaoapi "github.com/elastic/terraform-provider-elasticstack/internal/clients/kibanaoapi"
	"github.com/elastic/terraform-provider-elasticstack/internal/entitycore"
	"github.com/elastic/terraform-provider-elasticstack/internal/utils/typeutils"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *Resource) Create(ctx context.Context, request resource.CreateRequest, response *resource.CreateResponse) {
	var plan tfModel

	response.Diagnostics.Append(request.Plan.Get(ctx, &plan)...)
	if response.Diagnostics.HasError() {
		return
	}

	if r.Client() == nil {
		response.Diagnostics.AddError("Provider not configured", "Expected configured provider client factory")
		return
	}

	apiClient, diags := r.Client().GetKibanaClient(ctx, plan.KibanaConnection)
	response.Diagnostics.Append(diags...)
	if response.Diagnostics.HasError() {
		return
	}

	apiModel, diags := plan.toAPIModel()
	response.Diagnostics.Append(diags...)
	if response.Diagnostics.HasError() {
		return
	}

	response.Diagnostics.Append(entitycore.EnforceVersionRequirements(ctx, apiClient, &plan)...)
	if response.Diagnostics.HasError() {
		return
	}

	supportsGroupBy, groupByDiags := apiClient.EnforceMinVersion(ctx, SLOSupportsGroupByMinVersion)
	response.Diagnostics.Append(groupByDiags...)
	if response.Diagnostics.HasError() {
		return
	}
	if !supportsGroupBy {
		if len(apiModel.GroupBy) > 0 {
			response.Diagnostics.AddError(
				"Unsupported Elastic Stack version",
				"group_by is not supported in this version of the Elastic Stack. group_by requires "+SLOSupportsGroupByMinVersion.String()+" or higher.",
			)
			return
		}

		// Do not send group_by at all for stacks that don't support it.
		apiModel.GroupBy = nil
	}

	supportsMultipleGroupBy := false
	if supportsGroupBy {
		supportsMultipleGroupBy, groupByDiags = apiClient.EnforceMinVersion(ctx, SLOSupportsMultipleGroupByMinVersion)
		response.Diagnostics.Append(groupByDiags...)
		if response.Diagnostics.HasError() {
			return
		}
	}
	if len(apiModel.GroupBy) > 1 && !supportsMultipleGroupBy {
		response.Diagnostics.AddError(
			"Unsupported Elastic Stack version",
			"multiple group_by fields are not supported in this version of the Elastic Stack. Multiple group_by fields requires "+SLOSupportsMultipleGroupByMinVersion.String(),
		)
		return
	}

	oapi := apiClient.GetKibanaOapiClient()

	indicator, convErr := kibanaoapi.ResponseIndicatorToCreateIndicator(apiModel.Indicator)
	if convErr != nil {
		response.Diagnostics.AddError("Failed to convert indicator", convErr.Error())
		return
	}

	groupBy := kibanaoapi.TransformGroupBy(apiModel.GroupBy, supportsMultipleGroupBy)
	reqModel := kbapi.SLOsCreateSloRequest{
		Name:            apiModel.Name,
		Description:     apiModel.Description,
		Indicator:       indicator,
		TimeWindow:      apiModel.TimeWindow,
		BudgetingMethod: apiModel.BudgetingMethod,
		Objective:       apiModel.Objective,
		Settings:        apiModel.Settings,
		GroupBy:         groupBy,
		Tags:            typeutils.SliceRef(apiModel.Tags),
		Artifacts:       apiModel.Artifacts,
	}

	// Explicitly set SLO object id if provided, otherwise use the autogenerated ID from the Kibana API response.
	if apiModel.SloID != "" {
		reqModel.Id = &apiModel.SloID
	}

	desiredEnabled := plan.Enabled

	res, fwDiags := kibanaoapi.CreateSlo(ctx, oapi, apiModel.SpaceID, reqModel)
	response.Diagnostics.Append(fwDiags...)
	if response.Diagnostics.HasError() {
		return
	}

	compositeID := (&clients.CompositeID{ClusterID: apiModel.SpaceID, ResourceID: res.Id}).String()
	plan.ID = types.StringValue(compositeID)

	// Read back to populate computed fields.
	r.readAndPopulate(ctx, apiClient, &plan, &response.Diagnostics)
	if response.Diagnostics.HasError() {
		return
	}

	r.reconcileSloEnabledAfterWrite(ctx, apiClient, oapi, apiModel.SpaceID, res.Id, desiredEnabled, &plan, &response.Diagnostics)
	if response.Diagnostics.HasError() {
		return
	}

	response.Diagnostics.Append(response.State.Set(ctx, plan)...)
}
