"""Unit tests for check-pr-state.py.

Tests are designed to run without network or `gh` installed: they call the
pure `compute_payload()` function directly with hand-crafted fixture data.
A small handful of integration-shaped tests also exercise the resilience
and main() pathways using monkeypatched gh wrappers.

Run with:

    python -m pytest .agents/skills/pr-monitoring-loop/scripts/tests
"""

from __future__ import annotations

import importlib.util
import io
import json
import sys
from contextlib import redirect_stdout
from pathlib import Path

import pytest


SCRIPT = Path(__file__).resolve().parent.parent / "check-pr-state.py"


@pytest.fixture(scope="session")
def cps():
    spec = importlib.util.spec_from_file_location("check_pr_state", SCRIPT)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


# ---------------------------------------------------------------------------
# Fixture builders
# ---------------------------------------------------------------------------


HEAD_SHA = "headsha1234567890"
OLD_SHA = "oldsha000000000000"


def _pr(head_sha=HEAD_SHA, **overrides):
    base = {
        "number": 42,
        "url": "https://example.test/pulls/42",
        "state": "OPEN",
        "isDraft": False,
        "headRefName": "feature/x",
        "headRefOid": head_sha,
        "baseRefName": "main",
        "baseRefOid": "basesha",
        "reviewDecision": "REVIEW_REQUIRED",
        "mergeable": "MERGEABLE",
        "mergeStateStatus": "CLEAN",
        "labels": [],
        "statusCheckRollup": [],
        "title": "test PR",
        "updatedAt": "2026-05-07T00:00:00Z",
        "author": {"login": "human-dev"},
    }
    base.update(overrides)
    return base


def _comment(cid, login, body="hi", created="2026-05-07T01:00:00Z"):
    return {
        "id": cid,
        "user": {"login": login, "type": "Bot" if login.endswith("[bot]") else "User"},
        "body": body,
        "created_at": created,
        "updated_at": created,
    }


def _review_comment(cid, login, body="line note", created="2026-05-07T01:00:00Z"):
    return {
        "id": cid,
        "user": {"login": login, "type": "Bot" if login.endswith("[bot]") else "User"},
        "body": body,
        "path": "src/foo.go",
        "created_at": created,
        "updated_at": created,
    }


def _review(rid, login, state, commit_id=HEAD_SHA, submitted="2026-05-07T01:00:00Z", body=""):
    return {
        "id": rid,
        "user": {"login": login, "type": "Bot" if login.endswith("[bot]") else "User"},
        "state": state,
        "commit_id": commit_id,
        "submitted_at": submitted,
        "body": body,
    }


VERIFY_REPORT_BODY = (
    "## Verification Report: `some-change`\n\n"
    "Generated by OpenSpec verify (label) for issue #42"
)


def _verify_review(rid, state, commit_id=HEAD_SHA, submitted="2026-05-07T01:05:00Z"):
    """A review posted by the verify-openspec workflow (runs as github-actions[bot])."""
    return _review(
        rid,
        "github-actions[bot]",
        state,
        commit_id=commit_id,
        submitted=submitted,
        body=VERIFY_REPORT_BODY,
    )


def _label_event(action, at, label_name="verify-openspec"):
    return {
        "event": action,
        "created_at": at,
        "label": {"name": label_name},
    }


def _thread(tid, comments, resolved=False, outdated=False):
    return {
        "id": tid,
        "isResolved": resolved,
        "isOutdated": outdated,
        "path": "src/foo.go",
        "line": 1,
        "originalLine": 1,
        "comments": {"nodes": comments},
    }


def _thread_comment(node_id, db_id, login, created="2026-05-07T01:00:00Z"):
    return {
        "id": node_id,
        "databaseId": db_id,
        "author": {"login": login},
        "body": "please change",
        "createdAt": created,
        "updatedAt": created,
        "diffHunk": "@@",
        "path": "src/foo.go",
        "line": 1,
        "originalLine": 1,
        "outdated": False,
        "url": "https://example.test/c",
    }


def _empty_kwargs():
    return dict(
        repo={"owner": "o", "name": "r"},
        pr=_pr(),
        pr_check_data=[],
        commit_check_run_data=[],
        commit_status_data={},
        review_data=[],
        issue_comment_data=[],
        review_comment_data=[],
        thread_data=[],
        event_data=[],
        merge_conflict_data={"hasConflicts": False, "files": [], "analysisAvailable": True},
        state={},
    )


# ---------------------------------------------------------------------------
# new-since semantics (incl. bots are first-class)
# ---------------------------------------------------------------------------


def test_first_run_no_state_treats_all_comments_as_new(cps):
    kwargs = _empty_kwargs()
    kwargs["issue_comment_data"] = [
        _comment(1, "human-dev"),
        _comment(2, "macroscope[bot]"),
    ]
    kwargs["review_comment_data"] = [_review_comment(10, "verify-openspec[bot]")]
    payload, _ = cps.compute_payload(**kwargs)
    assert payload["summary"]["comments"]["newIssueComments"] == 2
    assert payload["summary"]["comments"]["newReviewComments"] == 1
    assert "issue_comments" in payload["summary"]["actionable"]
    assert "review_comments" in payload["summary"]["actionable"]


def test_seen_ids_silence_known_comments_and_bot_comments(cps):
    kwargs = _empty_kwargs()
    kwargs["issue_comment_data"] = [
        _comment(1, "human-dev"),
        _comment(2, "verify-openspec[bot]"),
    ]
    kwargs["state"] = {
        "seenIssueCommentIds": [1, 2],
        "lastPolledAt": "2026-05-07T05:00:00Z",
        "lastHeadSha": HEAD_SHA,
    }
    payload, _ = cps.compute_payload(**kwargs)
    assert payload["summary"]["comments"]["newIssueComments"] == 0
    assert "issue_comments" not in payload["summary"]["actionable"]


def test_bot_comment_actionable_first_then_silenced_after_state_persist(cps):
    bot_comment = _comment(99, "verify-openspec[bot]", body="something to address")
    kwargs = _empty_kwargs()
    kwargs["issue_comment_data"] = [bot_comment]
    payload, new_state = cps.compute_payload(**kwargs)
    assert payload["summary"]["comments"]["newIssueComments"] == 1
    assert "issue_comments" in payload["summary"]["actionable"]
    assert 99 in new_state["seenIssueCommentIds"]

    # Second run with the persisted state -> silenced.
    kwargs2 = _empty_kwargs()
    kwargs2["issue_comment_data"] = [bot_comment]
    kwargs2["state"] = new_state
    payload2, _ = cps.compute_payload(**kwargs2)
    assert payload2["summary"]["comments"]["newIssueComments"] == 0


def test_state_round_trip_caps_seen_ids(cps):
    kwargs = _empty_kwargs()
    kwargs["state"] = {"seenIssueCommentIds": list(range(2000))}
    kwargs["issue_comment_data"] = [_comment(2000, "human-dev")]
    _, new_state = cps.compute_payload(**kwargs)
    assert len(new_state["seenIssueCommentIds"]) <= cps.SEEN_ID_CAP
    assert 2000 in new_state["seenIssueCommentIds"]


# ---------------------------------------------------------------------------
# head-SHA pinning of checks
# ---------------------------------------------------------------------------


def test_commit_pinned_checks_are_canonical_when_present(cps):
    kwargs = _empty_kwargs()
    kwargs["pr_check_data"] = [
        # gh pr checks rollup row that is failing — but we should ignore it
        # because commit-pinned data wins.
        {"name": "old-failing", "bucket": "fail", "conclusion": "FAILURE"},
    ]
    kwargs["commit_check_run_data"] = [
        {"name": "lint", "status": "completed", "conclusion": "success"},
        {"name": "build", "status": "in_progress", "conclusion": None},
    ]
    payload, _ = cps.compute_payload(**kwargs)
    assert payload["summary"]["checks"]["source"] == "commit-pinned"
    assert payload["summary"]["checks"]["failed"] == 0
    assert payload["summary"]["checks"]["pending"] == 1
    assert payload["summary"]["checks"]["passed"] == 1
    assert "failed_checks" not in payload["summary"]["actionable"]


def test_falls_back_to_pr_checks_when_commit_pinned_unavailable(cps):
    kwargs = _empty_kwargs()
    kwargs["pr_check_data"] = [
        {"name": "lint", "bucket": "fail", "conclusion": "FAILURE"},
    ]
    payload, _ = cps.compute_payload(**kwargs)
    assert payload["summary"]["checks"]["source"] == "pr-checks"
    assert payload["summary"]["checks"]["failed"] == 1
    assert "failed_checks" in payload["summary"]["actionable"]


def test_combined_status_entries_are_normalized(cps):
    kwargs = _empty_kwargs()
    kwargs["commit_status_data"] = {
        "statuses": [
            {"context": "ci/legacy", "state": "failure"},
            {"context": "ci/extra", "state": "success"},
        ]
    }
    payload, _ = cps.compute_payload(**kwargs)
    assert payload["summary"]["checks"]["failed"] == 1
    assert payload["summary"]["checks"]["passed"] == 1


# ---------------------------------------------------------------------------
# effectiveDecision derivation
# ---------------------------------------------------------------------------


def test_effective_decision_later_approved_supersedes_earlier_changes_requested(cps):
    kwargs = _empty_kwargs()
    kwargs["review_data"] = [
        _review(1, "alice", "CHANGES_REQUESTED", submitted="2026-05-07T00:00:00Z"),
        _review(2, "alice", "APPROVED", submitted="2026-05-07T05:00:00Z"),
    ]
    payload, _ = cps.compute_payload(**kwargs)
    assert payload["summary"]["reviews"]["effectiveDecision"] == "APPROVED"
    assert "changes_requested" not in payload["summary"]["actionable"]


def test_effective_decision_one_reviewer_changes_requested_blocks(cps):
    kwargs = _empty_kwargs()
    kwargs["review_data"] = [
        _review(1, "alice", "APPROVED", submitted="2026-05-07T00:00:00Z"),
        _review(2, "bob", "CHANGES_REQUESTED", submitted="2026-05-07T01:00:00Z"),
    ]
    payload, _ = cps.compute_payload(**kwargs)
    assert payload["summary"]["reviews"]["effectiveDecision"] == "CHANGES_REQUESTED"
    assert "changes_requested" in payload["summary"]["actionable"]


def test_effective_decision_no_decision_reviews_yields_review_required(cps):
    kwargs = _empty_kwargs()
    kwargs["review_data"] = [_review(1, "alice", "COMMENTED")]
    payload, _ = cps.compute_payload(**kwargs)
    assert payload["summary"]["reviews"]["effectiveDecision"] == "REVIEW_REQUIRED"


# ---------------------------------------------------------------------------
# verifyOpenspec runState matrix
# ---------------------------------------------------------------------------


def test_verify_openspec_runstate_none_when_no_label_no_review(cps):
    payload, _ = cps.compute_payload(**_empty_kwargs())
    vo = payload["summary"]["reviews"]["verifyOpenspec"]
    assert vo["runState"] == "none"
    assert vo["approvalIsCurrent"] is False


def test_verify_openspec_runstate_pending_pickup_when_label_present(cps):
    kwargs = _empty_kwargs()
    kwargs["event_data"] = [_label_event("labeled", "2026-05-07T01:00:00Z")]
    payload, _ = cps.compute_payload(**kwargs)
    vo = payload["summary"]["reviews"]["verifyOpenspec"]
    assert vo["runState"] == "pending-pickup"
    assert vo["approvalIsCurrent"] is False


def test_verify_openspec_runstate_in_progress_after_workflow_removes_label(cps):
    """Label removed by workflow but no review submitted yet -> in-progress."""

    kwargs = _empty_kwargs()
    kwargs["event_data"] = [
        _label_event("labeled", "2026-05-07T01:00:00Z"),
        _label_event("unlabeled", "2026-05-07T01:00:30Z"),
    ]
    payload, _ = cps.compute_payload(**kwargs)
    vo = payload["summary"]["reviews"]["verifyOpenspec"]
    # critical: do NOT report `none` just because pr.labels no longer has it
    assert vo["runState"] == "in-progress"
    assert vo["approvalIsCurrent"] is False


def test_verify_openspec_runstate_approved_current(cps):
    kwargs = _empty_kwargs()
    kwargs["event_data"] = [
        _label_event("labeled", "2026-05-07T01:00:00Z"),
        _label_event("unlabeled", "2026-05-07T01:00:30Z"),
    ]
    kwargs["review_data"] = [_verify_review(7, "APPROVED")]
    payload, _ = cps.compute_payload(**kwargs)
    vo = payload["summary"]["reviews"]["verifyOpenspec"]
    assert vo["runState"] == "approved-current"
    assert vo["approvalIsCurrent"] is True
    assert vo["lastApprovalHeadSha"] == HEAD_SHA


def test_verify_openspec_runstate_approved_stale(cps):
    """Approval exists but for an older commit; no current label/run."""

    kwargs = _empty_kwargs()
    kwargs["review_data"] = [
        _verify_review(7, "APPROVED", commit_id=OLD_SHA, submitted="2026-05-06T00:00:00Z"),
    ]
    payload, _ = cps.compute_payload(**kwargs)
    vo = payload["summary"]["reviews"]["verifyOpenspec"]
    assert vo["runState"] == "approved-stale"
    assert vo["approvalIsCurrent"] is False


def test_verify_openspec_runstate_changes_requested(cps):
    kwargs = _empty_kwargs()
    kwargs["review_data"] = [_verify_review(7, "CHANGES_REQUESTED")]
    payload, _ = cps.compute_payload(**kwargs)
    vo = payload["summary"]["reviews"]["verifyOpenspec"]
    assert vo["runState"] == "changes-requested"
    assert vo["approvalIsCurrent"] is False


def test_verify_openspec_ignores_unrelated_github_actions_reviews(cps):
    """A review from github-actions[bot] WITHOUT the verify report body must
    not count as a verify-openspec approval. Verify-openspec runs as
    github-actions[bot] (the workflow's GITHUB_TOKEN identity) — content is
    what distinguishes verify reviews from any other workflow's reviews."""

    kwargs = _empty_kwargs()
    kwargs["review_data"] = [
        _review(
            7,
            "github-actions[bot]",
            "APPROVED",
            commit_id=HEAD_SHA,
            submitted="2026-05-07T01:05:00Z",
            body="LGTM from some-other-workflow",
        ),
    ]
    payload, _ = cps.compute_payload(**kwargs)
    vo = payload["summary"]["reviews"]["verifyOpenspec"]
    assert vo["runState"] == "none"
    assert vo["approvalIsCurrent"] is False


def test_verify_openspec_recognizes_review_by_body_marker(cps):
    """Even if the verification report wording changes slightly, the
    'OpenSpec verify' substring should be enough to identify it."""

    kwargs = _empty_kwargs()
    kwargs["review_data"] = [
        _review(
            7,
            "github-actions[bot]",
            "APPROVED",
            commit_id=HEAD_SHA,
            submitted="2026-05-07T01:05:00Z",
            body="Generated by OpenSpec verify (some new variant)",
        ),
    ]
    payload, _ = cps.compute_payload(**kwargs)
    assert payload["summary"]["reviews"]["verifyOpenspec"]["approvalIsCurrent"] is True


def test_verify_openspec_relabel_after_approval_resets_to_pending(cps):
    """If a label is re-applied AFTER an approval for the same head, runState
    resets to pending-pickup (i.e. workflow has been re-requested)."""

    kwargs = _empty_kwargs()
    kwargs["event_data"] = [
        _label_event("labeled", "2026-05-07T01:00:00Z"),
        _label_event("unlabeled", "2026-05-07T01:00:30Z"),
        _label_event("labeled", "2026-05-07T02:00:00Z"),
    ]
    kwargs["review_data"] = [_verify_review(7, "APPROVED")]
    payload, _ = cps.compute_payload(**kwargs)
    vo = payload["summary"]["reviews"]["verifyOpenspec"]
    assert vo["runState"] == "pending-pickup"
    assert vo["approvalIsCurrent"] is False


# ---------------------------------------------------------------------------
# Threads: distinguishing new vs. pending-fix
# ---------------------------------------------------------------------------


def test_unresolved_new_thread_is_actionable_first_time(cps):
    thread = _thread(
        "thread1",
        [_thread_comment("c1node", 555, "human-dev")],
    )
    kwargs = _empty_kwargs()
    kwargs["thread_data"] = [thread]
    payload, new_state = cps.compute_payload(**kwargs)
    threads = payload["summary"]["threads"]
    assert threads["unresolved"] == 1
    assert threads["unresolvedNew"] == 1
    assert "unresolved_review_threads" in payload["summary"]["actionable"]
    assert "thread1" in new_state["seenReviewThreadIds"]


def test_known_unresolved_thread_no_longer_actionable(cps):
    thread = _thread(
        "thread1",
        [_thread_comment("c1node", 555, "human-dev")],
    )
    kwargs = _empty_kwargs()
    kwargs["thread_data"] = [thread]
    kwargs["state"] = {
        "seenReviewThreadIds": ["thread1"],
        "lastPolledAt": "2026-05-07T05:00:00Z",
    }
    payload, _ = cps.compute_payload(**kwargs)
    threads = payload["summary"]["threads"]
    assert threads["unresolved"] == 1
    assert threads["unresolvedNew"] == 0
    assert "unresolved_review_threads" not in payload["summary"]["actionable"]


# ---------------------------------------------------------------------------
# Resilience
# ---------------------------------------------------------------------------


def test_main_emits_transient_exit_when_pr_view_returns_empty(cps, monkeypatch, capsys):
    monkeypatch.setattr(cps, "pr_view", lambda _: {})
    monkeypatch.setattr(cps, "repo_info", lambda: {"owner": "o", "name": "r"})
    rc = cps.main(["999"])
    assert rc == cps.EXIT_TRANSIENT
    out = capsys.readouterr().out
    body = json.loads(out)
    assert body.get("transient") is True


def test_main_emits_transient_exit_when_gh_repeatedly_fails(cps, monkeypatch, capsys):
    def failing(_args, *, default=None, allow_failure=False, retries=1):
        raise cps.TransientGhError(json.dumps({"error": "boom", "transient": True}))

    monkeypatch.setattr(cps, "gh_json", failing)
    rc = cps.main(["999"])
    assert rc == cps.EXIT_TRANSIENT
    out = capsys.readouterr().out
    body = json.loads(out)
    assert body.get("transient") is True


# ---------------------------------------------------------------------------
# State file round-trip via filesystem
# ---------------------------------------------------------------------------


def test_state_file_roundtrip(cps, tmp_path):
    p = tmp_path / "state.json"
    cps.save_state(str(p), {"pr": 1, "seenIssueCommentIds": [1, 2, 3]})
    loaded = cps.load_state(str(p))
    assert loaded["pr"] == 1
    assert loaded["seenIssueCommentIds"] == [1, 2, 3]


def test_state_file_load_missing_returns_empty(cps, tmp_path):
    p = tmp_path / "does-not-exist.json"
    assert cps.load_state(str(p)) == {}


def test_state_file_load_corrupt_returns_empty(cps, tmp_path):
    p = tmp_path / "corrupt.json"
    p.write_text("not json {")
    assert cps.load_state(str(p)) == {}


# ---------------------------------------------------------------------------
# Sanity on exposed thread comment ids (REST + GraphQL)
# ---------------------------------------------------------------------------


def test_review_threads_query_requests_database_id(cps):
    """The GraphQL query string must request both `id` and `databaseId` so
    workers can call REST in_reply_to (databaseId) AND resolveReviewThread
    (node id)."""

    src = SCRIPT.read_text()
    assert "databaseId" in src
