// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestCompileWorkflowExpandsNestedIncludes(t *testing.T) {
	rootDir := t.TempDir()

	workflowDir := filepath.Join(rootDir, ".github", "workflows-src", "example")
	if err := os.MkdirAll(filepath.Join(workflowDir, "scripts"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Join(rootDir, ".github", "workflows"), 0o755); err != nil {
		t.Fatal(err)
	}

	templatePath := filepath.Join(workflowDir, "workflow.md.tmpl")
	scriptPath := filepath.Join(workflowDir, "scripts", "example.inline.js")
	helperPath := filepath.Join(workflowDir, "helper.js")
	outputPath := filepath.Join(rootDir, ".github", "workflows", "example.md")

	writeFile(t, helperPath, "function helper() {\n  return 'ok';\n}\n")
	writeFile(t, scriptPath, "//include: ../helper.js\n\ncore.info(helper());\n")
	writeFile(t, templatePath, "---\nname: Example\n---\n\nwith:\n  x-script-include: scripts/example.inline.js\n")

	if _, err := CompileWorkflow(CompileOptions{
		TemplatePath: templatePath,
		OutputPath:   outputPath,
		RootDir:      rootDir,
	}); err != nil {
		t.Fatal(err)
	}

	generated := readFile(t, outputPath)

	assertContains(t, generated, "# This file is generated by")
	assertNotContains(t, generated, "//include:")
	assertContains(t, generated, "with:\n  script: |\n    function helper() {")
	assertContains(t, generated, "core.info(helper());")
}

func TestCompileWorkflowCheckModeReportsDrift(t *testing.T) {
	rootDir := t.TempDir()

	workflowDir := filepath.Join(rootDir, ".github", "workflows-src", "example")
	if err := os.MkdirAll(workflowDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Join(rootDir, ".github", "workflows"), 0o755); err != nil {
		t.Fatal(err)
	}

	templatePath := filepath.Join(workflowDir, "workflow.md.tmpl")
	outputPath := filepath.Join(rootDir, ".github", "workflows", "example.md")

	writeFile(t, templatePath, "---\nname: Example\n---\n\nwith:\n  script: |\n    core.info('hello');\n")
	writeFile(t, outputPath, "stale")

	result, err := CompileWorkflow(CompileOptions{
		TemplatePath: templatePath,
		OutputPath:   outputPath,
		RootDir:      rootDir,
		Check:        true,
	})
	if err != nil {
		t.Fatal(err)
	}

	if !result.Changed {
		t.Fatal("expected changed output to be reported")
	}
}

func TestCompileWorkflowDetectsIncludeCycles(t *testing.T) {
	rootDir := t.TempDir()

	workflowDir := filepath.Join(rootDir, ".github", "workflows-src", "example")
	if err := os.MkdirAll(filepath.Join(workflowDir, "scripts"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Join(rootDir, ".github", "workflows"), 0o755); err != nil {
		t.Fatal(err)
	}

	templatePath := filepath.Join(workflowDir, "workflow.md.tmpl")
	aPath := filepath.Join(workflowDir, "scripts", "a.js")
	bPath := filepath.Join(workflowDir, "scripts", "b.js")
	outputPath := filepath.Join(rootDir, ".github", "workflows", "example.md")

	writeFile(t, aPath, "//include: b.js\n")
	writeFile(t, bPath, "//include: a.js\n")
	writeFile(t, templatePath, "with:\n  x-script-include: scripts/a.js\n")

	_, err := CompileWorkflow(CompileOptions{
		TemplatePath: templatePath,
		OutputPath:   outputPath,
		RootDir:      rootDir,
	})
	if err == nil {
		t.Fatal("expected include cycle error")
	}

	assertContains(t, err.Error(), "include cycle detected")
}

func TestCompileWorkflowExpandsQuotedScriptInclude(t *testing.T) {
	rootDir := t.TempDir()

	workflowDir := filepath.Join(rootDir, ".github", "workflows-src", "example")
	if err := os.MkdirAll(filepath.Join(workflowDir, "scripts"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Join(rootDir, ".github", "workflows"), 0o755); err != nil {
		t.Fatal(err)
	}

	templatePath := filepath.Join(workflowDir, "workflow.md.tmpl")
	scriptPath := filepath.Join(workflowDir, "scripts", "example.inline.js")
	outputPath := filepath.Join(rootDir, ".github", "workflows", "example.md")

	writeFile(t, scriptPath, "core.info('quoted');\n")
	writeFile(t, templatePath, "with:\n  x-script-include: \"scripts/example.inline.js\"\n")

	if _, err := CompileWorkflow(CompileOptions{
		TemplatePath: templatePath,
		OutputPath:   outputPath,
		RootDir:      rootDir,
	}); err != nil {
		t.Fatal(err)
	}

	generated := readFile(t, outputPath)
	assertContains(t, generated, "with:\n  script: |\n    core.info('quoted');")
}

func writeFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

func readFile(t *testing.T, path string) string {
	t.Helper()
	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(content)
}

func assertContains(t *testing.T, content, expected string) {
	t.Helper()
	if !strings.Contains(content, expected) {
		t.Fatalf("expected content to contain %q\n\nactual:\n%s", expected, content)
	}
}

func assertNotContains(t *testing.T, content, expected string) {
	t.Helper()
	if strings.Contains(content, expected) {
		t.Fatalf("expected content not to contain %q\n\nactual:\n%s", expected, content)
	}
}
