// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

package main

import (
	"encoding/json"
	"errors"
	"fmt"
	"maps"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

const generatedHeaderPrefix = "# This file is generated by"

var includePattern = regexp.MustCompile(`(?m)^([ \t]*)//include:\s*(.+?)\s*$`)
var scriptIncludePattern = regexp.MustCompile(`(?m)^([ \t]*)x-script-include:\s*(.+?)\s*$`)

type manifestFile struct {
	Workflows []WorkflowConfig `json:"workflows"`
}

type WorkflowConfig struct {
	Template string `json:"template"`
	Output   string `json:"output"`
}

type CompileResult struct {
	OutputPath string
	Changed    bool
}

type CompileOptions struct {
	TemplatePath string
	OutputPath   string
	RootDir      string
	Check        bool
}

func CompileFromManifest(manifestPath, rootDir string, check bool) ([]CompileResult, error) {
	manifestContent, err := os.ReadFile(manifestPath)
	if err != nil {
		return nil, err
	}

	var manifest manifestFile
	if err := json.Unmarshal(manifestContent, &manifest); err != nil {
		return nil, err
	}

	results := make([]CompileResult, 0, len(manifest.Workflows))
	for _, workflow := range manifest.Workflows {
		result, err := CompileWorkflow(CompileOptions{
			TemplatePath: resolvePath(rootDir, workflow.Template),
			OutputPath:   resolvePath(rootDir, workflow.Output),
			RootDir:      rootDir,
			Check:        check,
		})
		if err != nil {
			return nil, err
		}
		results = append(results, result)
	}

	return results, nil
}

func CompileWorkflow(opts CompileOptions) (CompileResult, error) {
	templateContent, err := os.ReadFile(opts.TemplatePath)
	if err != nil {
		return CompileResult{}, err
	}

	expandedContent, err := expandIncludes(
		string(templateContent),
		opts.TemplatePath,
		opts.RootDir,
		map[string]bool{opts.TemplatePath: true},
	)
	if err != nil {
		return CompileResult{}, err
	}

	generatedContent := injectGeneratedHeader(
		expandedContent,
		createGeneratedHeader(opts.TemplatePath, opts.RootDir),
	)

	if opts.Check {
		currentOutput, err := os.ReadFile(opts.OutputPath)
		if err != nil && !errors.Is(err, os.ErrNotExist) {
			return CompileResult{}, err
		}

		return CompileResult{
			OutputPath: opts.OutputPath,
			Changed:    string(currentOutput) != generatedContent,
		}, nil
	}

	if err := os.WriteFile(opts.OutputPath, []byte(generatedContent), 0o644); err != nil {
		return CompileResult{}, err
	}

	return CompileResult{
		OutputPath: opts.OutputPath,
		Changed:    true,
	}, nil
}

func expandIncludes(content, currentFilePath, rootDir string, seen map[string]bool) (string, error) {
	content, err := expandScriptIncludes(content, currentFilePath, rootDir, seen)
	if err != nil {
		return "", err
	}

	matches := includePattern.FindAllStringSubmatchIndex(content, -1)
	if len(matches) == 0 {
		return content, nil
	}

	var result strings.Builder
	lastIndex := 0

	for _, match := range matches {
		fullStart, fullEnd := match[0], match[1]
		indentStart, indentEnd := match[2], match[3]
		pathStart, pathEnd := match[4], match[5]

		result.WriteString(content[lastIndex:fullStart])

		indent := content[indentStart:indentEnd]
		relativeIncludePath := strings.TrimSpace(content[pathStart:pathEnd])
		resolvedIncludePath := filepath.Clean(filepath.Join(filepath.Dir(currentFilePath), relativeIncludePath))

		if seen[resolvedIncludePath] {
			return "", fmt.Errorf(
				"include cycle detected while expanding %s",
				normalizeRelativePath(rootDir, resolvedIncludePath),
			)
		}

		includedContent, err := os.ReadFile(resolvedIncludePath)
		if err != nil {
			return "", err
		}

		nextSeen := cloneSeen(seen)
		nextSeen[resolvedIncludePath] = true

		expandedInclude, err := expandIncludes(string(includedContent), resolvedIncludePath, rootDir, nextSeen)
		if err != nil {
			return "", err
		}

		result.WriteString(indentLines(expandedInclude, indent))
		lastIndex = fullEnd
	}

	result.WriteString(content[lastIndex:])
	return result.String(), nil
}

func expandScriptIncludes(content, currentFilePath, rootDir string, seen map[string]bool) (string, error) {
	matches := scriptIncludePattern.FindAllStringSubmatchIndex(content, -1)
	if len(matches) == 0 {
		return content, nil
	}

	var result strings.Builder
	lastIndex := 0

	for _, match := range matches {
		fullStart, fullEnd := match[0], match[1]
		indentStart, indentEnd := match[2], match[3]
		pathStart, pathEnd := match[4], match[5]

		result.WriteString(content[lastIndex:fullStart])

		indent := content[indentStart:indentEnd]
		relativeIncludePath := trimOptionalQuotes(strings.TrimSpace(content[pathStart:pathEnd]))
		resolvedIncludePath := filepath.Clean(filepath.Join(filepath.Dir(currentFilePath), relativeIncludePath))

		if seen[resolvedIncludePath] {
			return "", fmt.Errorf(
				"include cycle detected while expanding %s",
				normalizeRelativePath(rootDir, resolvedIncludePath),
			)
		}

		includedContent, err := os.ReadFile(resolvedIncludePath)
		if err != nil {
			return "", err
		}

		nextSeen := cloneSeen(seen)
		nextSeen[resolvedIncludePath] = true

		expandedInclude, err := expandIncludes(string(includedContent), resolvedIncludePath, rootDir, nextSeen)
		if err != nil {
			return "", err
		}

		result.WriteString(indent + "script: |\n")
		result.WriteString(indentLines(expandedInclude, indent+"  "))
		lastIndex = fullEnd
	}

	result.WriteString(content[lastIndex:])
	return result.String(), nil
}

func cloneSeen(seen map[string]bool) map[string]bool {
	cloned := make(map[string]bool, len(seen))
	maps.Copy(cloned, seen)
	return cloned
}

func trimOptionalQuotes(value string) string {
	if len(value) >= 2 {
		if (value[0] == '"' && value[len(value)-1] == '"') || (value[0] == '\'' && value[len(value)-1] == '\'') {
			return value[1 : len(value)-1]
		}
	}
	return value
}

func indentLines(content, indent string) string {
	lines := strings.Split(content, "\n")
	for i, line := range lines {
		lines[i] = indent + line
	}
	return strings.Join(lines, "\n")
}

func injectGeneratedHeader(content, headerLine string) string {
	if strings.HasPrefix(content, "---\n") {
		return strings.Replace(content, "---\n", fmt.Sprintf("---\n%s\n", headerLine), 1)
	}
	return headerLine + "\n" + content
}

func createGeneratedHeader(templatePath, rootDir string) string {
	toolPath := resolvePath(rootDir, filepath.Join("scripts", "compile-workflow-sources", "main.go"))
	return fmt.Sprintf(
		"%s `%s` from `%s`. Do not edit directly.",
		generatedHeaderPrefix,
		normalizeRelativePath(rootDir, toolPath),
		normalizeRelativePath(rootDir, templatePath),
	)
}

func resolvePath(rootDir, targetPath string) string {
	if filepath.IsAbs(targetPath) {
		return filepath.Clean(targetPath)
	}
	return filepath.Clean(filepath.Join(rootDir, targetPath))
}

func normalizeRelativePath(rootDir, targetPath string) string {
	relative, err := filepath.Rel(rootDir, targetPath)
	if err != nil {
		return filepath.ToSlash(targetPath)
	}
	return filepath.ToSlash(relative)
}
