// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestCompileWorkflowExpandsNestedIncludes(t *testing.T) {
	rootDir := t.TempDir()

	workflowDir := filepath.Join(rootDir, ".github", "workflows-src", "example")
	if err := os.MkdirAll(filepath.Join(workflowDir, "scripts"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Join(rootDir, ".github", "workflows"), 0o755); err != nil {
		t.Fatal(err)
	}

	templatePath := filepath.Join(workflowDir, "workflow.md.tmpl")
	scriptPath := filepath.Join(workflowDir, "scripts", "example.inline.js")
	helperPath := filepath.Join(workflowDir, "helper.js")
	outputPath := filepath.Join(rootDir, ".github", "workflows", "example.md")

	writeFile(t, helperPath, "function helper() {\n  return 'ok';\n}\n")
	writeFile(t, scriptPath, "//include: ../helper.js\n\ncore.info(helper());\n")
	writeFile(t, templatePath, "---\nname: Example\n---\n\nwith:\n  x-script-include: scripts/example.inline.js\n")

	if _, err := CompileWorkflow(CompileOptions{
		TemplatePath: templatePath,
		OutputPath:   outputPath,
		RootDir:      rootDir,
	}); err != nil {
		t.Fatal(err)
	}

	generated := readFile(t, outputPath)

	assertContains(t, generated, "# This file is generated by")
	assertNotContains(t, generated, "//include:")
	assertContains(t, generated, "with:\n  script: |\n    function helper() {")
	assertContains(t, generated, "core.info(helper());")
}

func TestCompileWorkflowCheckModeReportsDrift(t *testing.T) {
	rootDir := t.TempDir()

	workflowDir := filepath.Join(rootDir, ".github", "workflows-src", "example")
	if err := os.MkdirAll(workflowDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Join(rootDir, ".github", "workflows"), 0o755); err != nil {
		t.Fatal(err)
	}

	templatePath := filepath.Join(workflowDir, "workflow.md.tmpl")
	outputPath := filepath.Join(rootDir, ".github", "workflows", "example.md")

	writeFile(t, templatePath, "---\nname: Example\n---\n\nwith:\n  script: |\n    core.info('hello');\n")
	writeFile(t, outputPath, "stale")

	result, err := CompileWorkflow(CompileOptions{
		TemplatePath: templatePath,
		OutputPath:   outputPath,
		RootDir:      rootDir,
		Check:        true,
	})
	if err != nil {
		t.Fatal(err)
	}

	if !result.Changed {
		t.Fatal("expected changed output to be reported")
	}
	if result.Diff != "" {
		t.Fatalf("expected diff to be empty without verbose output, got:\n%s", result.Diff)
	}
}

func TestCompileWorkflowCheckModeVerboseReportsDiff(t *testing.T) {
	rootDir := t.TempDir()

	workflowDir := filepath.Join(rootDir, ".github", "workflows-src", "example")
	if err := os.MkdirAll(workflowDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Join(rootDir, ".github", "workflows"), 0o755); err != nil {
		t.Fatal(err)
	}

	templatePath := filepath.Join(workflowDir, "workflow.md.tmpl")
	outputPath := filepath.Join(rootDir, ".github", "workflows", "example.md")

	writeFile(t, templatePath, "---\nname: Example\n---\n\nwith:\n  script: |\n    core.info('hello');\n")
	writeFile(t, outputPath, "stale\n")

	result, err := CompileWorkflow(CompileOptions{
		TemplatePath: templatePath,
		OutputPath:   outputPath,
		RootDir:      rootDir,
		Check:        true,
		Verbose:      true,
	})
	if err != nil {
		t.Fatal(err)
	}

	if !result.Changed {
		t.Fatal("expected changed output to be reported")
	}

	assertContains(t, result.Diff, "--- a/.github/workflows/example.md")
	assertContains(t, result.Diff, "+++ b/.github/workflows/example.md")
	assertContains(t, result.Diff, "-stale")
	assertContains(t, result.Diff, "+# This file is generated by")
}

func TestRunCheckModeVerboseControlsDiffOutput(t *testing.T) {
	rootDir := t.TempDir()

	workflowDir := filepath.Join(rootDir, ".github", "workflows-src", "example")
	if err := os.MkdirAll(workflowDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Join(rootDir, ".github", "workflows"), 0o755); err != nil {
		t.Fatal(err)
	}

	templatePath := filepath.Join(workflowDir, "workflow.md.tmpl")
	outputPath := filepath.Join(rootDir, ".github", "workflows", "example.md")

	writeFile(t, templatePath, "---\nname: Example\n---\n\nwith:\n  script: |\n    core.info('hello');\n")
	writeFile(t, outputPath, "stale\n")

	testCases := []struct {
		name        string
		args        []string
		expected    []string
		notExpected []string
	}{
		{
			name: "without verbose",
			args: []string{
				"--check",
				"--root", rootDir,
				"--template", templatePath,
				"--output", outputPath,
			},
			expected: []string{
				"generated workflow sources are out of date:",
				"- .github/workflows/example.md",
			},
			notExpected: []string{
				"--- a/.github/workflows/example.md",
			},
		},
		{
			name: "with verbose",
			args: []string{
				"--check",
				"--verbose",
				"--root", rootDir,
				"--template", templatePath,
				"--output", outputPath,
			},
			expected: []string{
				"generated workflow sources are out of date:",
				"- .github/workflows/example.md",
				"--- a/.github/workflows/example.md",
				"+++ b/.github/workflows/example.md",
			},
		},
	}

	for _, testCase := range testCases {
		t.Run(testCase.name, func(t *testing.T) {
			stderr := openTempFile(t)
			err := run(testCase.args, stderr, stderr)
			if err == nil {
				t.Fatal("expected check mode to report drift")
			}

			for _, expected := range testCase.expected {
				assertContains(t, err.Error(), expected)
			}
			for _, unexpected := range testCase.notExpected {
				assertNotContains(t, err.Error(), unexpected)
			}
		})
	}
}

func TestCompileWorkflowDetectsIncludeCycles(t *testing.T) {
	rootDir := t.TempDir()

	workflowDir := filepath.Join(rootDir, ".github", "workflows-src", "example")
	if err := os.MkdirAll(filepath.Join(workflowDir, "scripts"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Join(rootDir, ".github", "workflows"), 0o755); err != nil {
		t.Fatal(err)
	}

	templatePath := filepath.Join(workflowDir, "workflow.md.tmpl")
	aPath := filepath.Join(workflowDir, "scripts", "a.js")
	bPath := filepath.Join(workflowDir, "scripts", "b.js")
	outputPath := filepath.Join(rootDir, ".github", "workflows", "example.md")

	writeFile(t, aPath, "//include: b.js\n")
	writeFile(t, bPath, "//include: a.js\n")
	writeFile(t, templatePath, "with:\n  x-script-include: scripts/a.js\n")

	_, err := CompileWorkflow(CompileOptions{
		TemplatePath: templatePath,
		OutputPath:   outputPath,
		RootDir:      rootDir,
	})
	if err == nil {
		t.Fatal("expected include cycle error")
	}

	assertContains(t, err.Error(), "include cycle detected")
}

func TestProviderWorkflowContainsGateJob(t *testing.T) {
	rootDir := filepath.Join("..", "..")
	templatePath := filepath.Join(rootDir, ".github", "workflows-src", "provider", "workflow.yml.tmpl")
	outputPath := filepath.Join(t.TempDir(), "provider.yml")

	if _, err := CompileWorkflow(CompileOptions{
		TemplatePath: templatePath,
		OutputPath:   outputPath,
		RootDir:      rootDir,
	}); err != nil {
		t.Fatal(err)
	}

	generated := readFile(t, outputPath)
	assertContains(t, generated, "  gate:")
	assertContains(t, generated, "    needs: [classify, build, lint, test]")
	assertContains(t, generated, "    if: always()")
	assertContains(t, generated, "actions/github-script")
	assertContains(t, generated, "function gateProvider")
}

func TestWorkflowsWorkflowContainsGateJob(t *testing.T) {
	rootDir := filepath.Join("..", "..")
	templatePath := filepath.Join(rootDir, ".github", "workflows-src", "workflows", "workflow.yml.tmpl")
	outputPath := filepath.Join(t.TempDir(), "workflows.yml")

	if _, err := CompileWorkflow(CompileOptions{
		TemplatePath: templatePath,
		OutputPath:   outputPath,
		RootDir:      rootDir,
	}); err != nil {
		t.Fatal(err)
	}

	generated := readFile(t, outputPath)
	assertContains(t, generated, "  gate:")
	assertContains(t, generated, "    needs: [classify, test]")
	assertContains(t, generated, "    if: always()")
	assertContains(t, generated, "actions/github-script")
	assertContains(t, generated, "function gateWorkflows")
}

func TestOpenspecWorkflowContainsGateJob(t *testing.T) {
	rootDir := filepath.Join("..", "..")
	templatePath := filepath.Join(rootDir, ".github", "workflows-src", "openspec", "workflow.yml.tmpl")
	outputPath := filepath.Join(t.TempDir(), "openspec.yml")

	if _, err := CompileWorkflow(CompileOptions{
		TemplatePath: templatePath,
		OutputPath:   outputPath,
		RootDir:      rootDir,
	}); err != nil {
		t.Fatal(err)
	}

	generated := readFile(t, outputPath)
	assertContains(t, generated, "  gate:")
	assertContains(t, generated, "    needs: [validate]")
	assertContains(t, generated, "    if: always()")
}

func TestCompileWorkflowExpandsQuotedScriptInclude(t *testing.T) {
	rootDir := t.TempDir()

	workflowDir := filepath.Join(rootDir, ".github", "workflows-src", "example")
	if err := os.MkdirAll(filepath.Join(workflowDir, "scripts"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Join(rootDir, ".github", "workflows"), 0o755); err != nil {
		t.Fatal(err)
	}

	templatePath := filepath.Join(workflowDir, "workflow.md.tmpl")
	scriptPath := filepath.Join(workflowDir, "scripts", "example.inline.js")
	outputPath := filepath.Join(rootDir, ".github", "workflows", "example.md")

	writeFile(t, scriptPath, "core.info('quoted');\n")
	writeFile(t, templatePath, "with:\n  x-script-include: \"scripts/example.inline.js\"\n")

	if _, err := CompileWorkflow(CompileOptions{
		TemplatePath: templatePath,
		OutputPath:   outputPath,
		RootDir:      rootDir,
	}); err != nil {
		t.Fatal(err)
	}

	generated := readFile(t, outputPath)
	assertContains(t, generated, "with:\n  script: |\n    core.info('quoted');")
}

func writeFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

func readFile(t *testing.T, path string) string {
	t.Helper()
	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(content)
}

func openTempFile(t *testing.T) *os.File {
	t.Helper()
	file, err := os.CreateTemp(t.TempDir(), "compile-workflow-sources-*")
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() {
		_ = file.Close()
	})
	return file
}

func assertContains(t *testing.T, content, expected string) {
	t.Helper()
	if !strings.Contains(content, expected) {
		t.Fatalf("expected content to contain %q\n\nactual:\n%s", expected, content)
	}
}

func assertNotContains(t *testing.T, content, expected string) {
	t.Helper()
	if strings.Contains(content, expected) {
		t.Fatalf("expected content not to contain %q\n\nactual:\n%s", expected, content)
	}
}
